spring.application.name=product-service
server.port=8080

spring.datasource.url=jdbc:h2:mem:productdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.pattern.console=%d{HH:mm:ss} %-5level [corr:%X{correlationId}] [trace:%X{traceId}] [span:%X{spanId}] %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.prometheus.metrics.export.enabled=true
management.info.env.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

info.app.name=product-service
info.app.description=Product microservice for Assignment 4
